import type { Metadata } from "next";
import "./globals.css";




export const metadata: Metadata = {
  title: "Figma into Nextjs",
  description: "Generated by Donia Batool",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        {children}
      </body>
    </html>
  );
}
